name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    
    - name: Build the Docker image
      run: |
        chmod +x ./container/build.sh
      
        ./container/build.sh --framework vllm

        docker tag dynamo:latest-vllm luckymrwang/dynamo:latest-vllm
    
        docker push luckymrwang/dynamo:latest-vllm
      
      
