name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
      echo "==Debug Check files =="
      ls -la ./container/

      echo "=== Set permissions ==="
      chmod +x ./container/build.sh
      
      ./container/build.sh --framework vllm
      
